version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restapi
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: restapi_app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/restapi?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data:
